### ISSUE TITLE
libvirt-bin is missing

### ISSUE THREAD

**Issue by jsoyer** [lorin/devstack-vm#10]
Hello,

It seems that you use virsh in your Vagrantfile in the provision section for removing default network but you don't push it with ansible in the box.

Maybe you can add this in devstack.yml : 

name: install libvirt-bin
      apt: "name=libvirt-bin update_cache=yes"
      sudo: True

Thanks.

**Comment by lorin** [comment]
Fixed this locally, but forgot to push it. devstack installs libvirt-bin, so just moved this call to after devstack setup is complete.
