### ISSUE TITLE
become is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by Jonher937** [lorin/devstack-vm#27]
Commit https://github.com/lorin/devstack-vm/commit/c29c3237ec547c788190e01444161431a6e4134a breaks the build for me. 

```
ERROR: become is not a legal parameter in an Ansible task or handler
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

**Comment by lorin** [comment]
@Jonher937 Which version of Ansible are you using? These changes were updated for version 2 of Ansible.

**Comment by Jonher937** [comment]
It seems like "1.7.2+dfsg-2" is distributed in the stable repo for Debian: https://packages.debian.org/jessie/ansible

I'm not familiar with Ansible and though it was in the VM and not on the host :)
I upgraded ansible using pip and now "become" works as expected. 
Thanks!
