### ISSUE TITLE
Upgraded to cirros-0.3.2 and ubuntu thrusty

### ISSUE THREAD

**Issue by homlhl** [lorin/devstack-vm#7]
index 7028c5c..5b0925f 100644
--- a/README.md
+++ b/README.md
@@ -173,7 +173,7 @@ Source the credentials of the "demo" user and boot an instance.
 
     source demo.openrc
     nova keypair-add --pub-key ~/.ssh/id_rsa.pub mykey
-    nova boot --flavor m1.nano --image cirros-0.3.1-x86_64-uec --key-name mykey cirros
+    nova boot --flavor m1.tiny --image cirros-0.3.2-x86_64-uec --key-name mykey cirros
 
 Once the instance has booted, get its ID.
 
diff --git a/Vagrantfile b/Vagrantfile
index cb3206b..2f7aff3 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -4,8 +4,8 @@
 
 Vagrant.configure("2") do |config|
 
-    config.vm.box = "saucy64"
-    config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box"
+    config.vm.box = "trusty64"
+    config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
     # eth1, this will be the endpoint
     config.vm.network :private_network, ip: "192.168.27.100"
     # eth2, this will be the OpenStack "public" network, use DevStack default
diff --git a/boot-cirros.py b/boot-cirros.py
index d385f37..1c20214 100755
--- a/boot-cirros.py
+++ b/boot-cirros.py
@@ -45,7 +45,7 @@ if not nova.keypairs.findall(name="mykey"):
 print("done")
 
 print("Booting cirros instance...", end='')
-image = nova.images.find(name="cirros-0.3.1-x86_64-uec")
+image = nova.images.find(name="cirros-0.3.2-x86_64-uec")
 flavor = nova.flavors.find(name="m1.tiny")
 instance = nova.servers.create(name="cirros", image=image, flavor=flavor,
                               key_name="mykey")
diff --git a/devstack.yaml b/devstack.yaml
index 464cbd1..29be5ca 100644
--- a/devstack.yaml
+++ b/devstack.yaml
@@ -3,7 +3,7 @@
   vars:
     devstack_repo: git://github.com/openstack-dev/devstack.git
     public_ip: 192.168.27.100
-    version: stable/havana
+    version: stable/icehouse
     neutron: True
     swift: True
     security_groups: False
@@ -26,7 +26,7 @@
       sudo: True

**Comment by lorin** [comment]
Thanks, applied as f8afc4df4753f8090fd801b7f057f2cba938d310.
